name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install -y libcppunit-dev qtcreator libqt5webkit5-dev  qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
    - name: make install
      run: qmake SSD1306_Emulator.pro  && make
